# Generated by Django 4.2.14 on 2024-07-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240713_1634'),
        ('users', '0006_alter_user_groups_alter_user_id_and_more'),
    ]

    operations = [
    ]
