# Generated by Django 3.2 on 2024-07-23 21:04

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240722_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[posts.validators.validate_year], verbose_name='Год выхода'),
        ),
    ]
