# Generated by Django 3.2 on 2024-07-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240723_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
    ]
